package com.epul.ergosum.model;

// Generated 24 avr. 2014 11:38:54 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Categorie generated by hbm2java
 */
@Entity
@Table(name = "CATEGORIE")
public class Categorie implements java.io.Serializable {
	// mapping ok
	private static final long serialVersionUID = 3235302993284638500L;
	private String codecateg;
	private String libcateg;
	private Set<Jouet> jouets = new HashSet<Jouet>(0);

	public Categorie() {
	}

	public Categorie(String codecateg) {
		this.codecateg = codecateg;
	}

	public Categorie(String codecateg, String libcateg, Set<Jouet> jouets) {
		this.codecateg = codecateg;
		this.libcateg = libcateg;
		this.jouets = jouets;
	}

	@Id
	@Column(name = "CODECATEG")
	public String getCodecateg() {
		return this.codecateg;
	}

	public void setCodecateg(String codecateg) {
		this.codecateg = codecateg;
	}

	public String getLibcateg() {
		return this.libcateg;
	}

	public void setLibcateg(String libcateg) {
		this.libcateg = libcateg;
	}

	@OneToMany(cascade = CascadeType.ALL, mappedBy = "categorie")
	public Set<Jouet> getJouets() {
		return this.jouets;
	}

	public void setJouets(Set<Jouet> jouets) {
		this.jouets = jouets;
	}

}
