package com.epul.ergosum.model;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

// Generated 24 avr. 2014 11:38:54 by Hibernate Tools 4.0.0

/**
 * Comporte generated by hbm2java
 */
@Entity
@Table(name = "Comporte")
public class Comporte implements java.io.Serializable {

	private static final long serialVersionUID = -8658497389198494394L;
	private ComporteId id;
	private Jouet jouet;
	private Catalogue catalogue;
	private Integer quantite;

	public Comporte() {
	}

	public Comporte(ComporteId id, Jouet jouet, Catalogue catalogue) {
		this.id = id;
		this.jouet = jouet;
		this.catalogue = catalogue;
	}

	public Comporte(ComporteId id, Jouet jouet, Catalogue catalogue,
			Integer quantite) {
		this.id = id;
		this.jouet = jouet;
		this.catalogue = catalogue;
		this.quantite = quantite;
	}

	@Id
	// @Column(name = "")
	public ComporteId getId() {
		return this.id;
	}

	public void setId(ComporteId id) {
		this.id = id;
	}

	@ManyToOne
	@JoinColumn(name = "NUMERO")
	public Jouet getJouet() {
		return this.jouet;
	}

	public void setJouet(Jouet jouet) {
		this.jouet = jouet;
	}

	public Catalogue getCatalogue() {
		return this.catalogue;
	}

	public void setCatalogue(Catalogue catalogue) {
		this.catalogue = catalogue;
	}

	public Integer getQuantite() {
		return this.quantite;
	}

	public void setQuantite(Integer quantite) {
		this.quantite = quantite;
	}

}
